"""Rename metadata to additional_metadata in StructuredPost

Revision ID: 19a7552ef238
Revises: 
Create Date: 2025-11-28 12:23:54.928232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a7552ef238'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ブログの名称'),
    sa.Column('hatena_id', sa.String(length=100), nullable=False, comment='はてなID'),
    sa.Column('hatena_blog_id', sa.String(length=100), nullable=False, comment='はてなブログID'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='はてなブログAtomPub APIキー（暗号化推奨）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hatena_blog_id')
    )
    op.create_table('gemini_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False, comment='APIキーのハッシュ値'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment='使用モデル名'),
    sa.Column('endpoint', sa.String(length=64), nullable=False, comment='使用エンドポイント (vision, textなど)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='API呼び出し成功フラグ'),
    sa.Column('status', sa.String(length=64), nullable=False, comment='結果ステータス (OK, errorなど)'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='応答時間 (ミリ秒)'),
    sa.Column('prompt_chars', sa.Integer(), nullable=True, comment='プロンプトの文字数'),
    sa.Column('response_chars', sa.Integer(), nullable=True, comment='応答の文字数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='エラーメッセージ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=255), nullable=False, comment='LINEのユーザーID'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='LINEでの表示名'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_user_id')
    )
    op.create_table('hatena_blog_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='ブログID'),
    sa.Column('hatena_entry_id', sa.String(length=255), nullable=False, comment='はてなブログの記事エントリーID'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='記事タイトル'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='記事URL'),
    sa.Column('published', sa.DateTime(), nullable=True, comment='公開日時'),
    sa.Column('updated', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='コンテンツのハッシュ値（変更検出用）'),
    sa.Column('categories', sa.Text(), nullable=True, comment='カテゴリ（カンマ区切り）'),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='最終同期日時'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hatena_entry_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_message_id', sa.String(length=255), nullable=False, comment='LINEのメッセージID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='メッセージ種別（text, image, videoなど）'),
    sa.Column('content', sa.Text(), nullable=True, comment='テキストメッセージの本文'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_message_id')
    )
    op.create_table('structured_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='ブログID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作成者ユーザーID'),
    sa.Column('reference_id', sa.String(length=100), nullable=True, comment='外部参照用ID (@123 などで使用)'),
    sa.Column('theme', sa.Text(), nullable=False, comment='記事のテーマ'),
    sa.Column('structure', sa.Text(), nullable=False, comment='記事構成 (JSON)'),
    sa.Column('products', sa.Text(), nullable=False, comment='紹介商品リスト (JSON)'),
    sa.Column('key_messages', sa.Text(), nullable=False, comment='キーメッセージ (JSON)'),
    sa.Column('content_elements', sa.Text(), nullable=True, comment='コンテンツ要素 (JSON)'),
    sa.Column('affiliate_strategy', sa.Text(), nullable=True, comment='アフィリエイト戦略 (JSON)'),
    sa.Column('additional_metadata', sa.Text(), nullable=False, comment='追加メタデータ (JSON: tone, target_audience, etc.)'),
    sa.Column('target_keywords', sa.Text(), nullable=True, comment='ターゲットキーワード (JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('user_blog_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=True, comment='投稿権限の有無'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'blog_id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='関連メッセージID'),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='アセット種別（image, video）'),
    sa.Column('local_path', sa.String(length=500), nullable=True, comment='サーバー上の一時保存パス'),
    sa.Column('external_url', sa.String(length=500), nullable=True, comment='Imgurなどの外部ストレージURL'),
    sa.Column('description', sa.Text(), nullable=True, comment='AIによる画像解析結果やキャプション'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='投稿先ブログID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作成者ユーザーID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='記事タイトル'),
    sa.Column('content', sa.Text(), nullable=False, comment='記事本文 (HTML)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='記事の状態 (draft, published, error)'),
    sa.Column('hatena_entry_id', sa.String(length=255), nullable=True, comment='はてなブログの記事エントリーID'),
    sa.Column('hatena_entry_url', sa.String(length=500), nullable=True, comment='はてなブログの記事URL'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='公開日時'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新日時'),
    sa.Column('quality_check_status', sa.String(length=50), nullable=True, comment='品質チェック状態 (pending, passed, failed)'),
    sa.Column('quality_check_results', sa.Text(), nullable=True, comment='品質チェック結果 (JSON形式)'),
    sa.Column('is_repost', sa.Boolean(), nullable=True, comment='リポスト記事かどうか'),
    sa.Column('source_structured_post_id', sa.Integer(), nullable=True, comment='リポスト元の構造化投稿ID'),
    sa.Column('repost_style_prompt', sa.Text(), nullable=True, comment='リポスト時のスタイルプロンプト'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['source_structured_post_id'], ['structured_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hatena_entry_id')
    )
    op.create_table('post_source_messages',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_source_messages')
    op.drop_table('blog_posts')
    op.drop_table('assets')
    op.drop_table('user_blog_permissions')
    op.drop_table('structured_posts')
    op.drop_table('messages')
    op.drop_table('hatena_blog_entries')
    op.drop_table('users')
    op.drop_table('gemini_usage_logs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
